# application bootstrap configuration
spring:
  application:
    name: ea-organisation-service
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888

# eureka configuration
eureka:
  instance:
    prefer-ip-address: true                                 #register the IP of the service rather than the server name.
  client:
    register-with-eureka: true                              #register the service with Eureka
    fetch-registry: true                                    #fetch a local copy of the registry, cache the registry locally instead of calling the Eureka service with every lookup
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}           #location of the Eureka Service

# application configuration
logging:
  level:
    root: info